version: '2.0'
networks:
  webphp:
    driver: bridge
    ipam:
      config:
        - subnet: 10.201.0.0/16
          gateway: 10.201.0.1
services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: c-nginx
        image: nginx:latest
        restart: always
        ports:
            - "81:80"
            - "443:443"
            - "7777:7777"
        volumes:
            - ./code:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./nginx/ssl:/etc/nginx/ssl
            - ./nginx/log/nginx:/var/log/nginx
        links:
            - php
        networks:
            webphp:
                ipv4_address: 10.201.0.2
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: c-php
        restart: always
        volumes:
            - ./code:/var/www
            - ./php:/usr/local/etc/php/
        links: 
            - mysql
            - redis
        networks:
            webphp:
                ipv4_address: 10.201.0.3
    mysql: 
        container_name: c-mysql
        image: mysql:latest
        ports: 
            - "3308:3306"
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=projectlaravel
            - MYSQL_ROOT_PASSWORD=123456
        networks:
            webphp:
                ipv4_address: 10.201.0.4
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: 'c-phpmyadmin'
        links:
          - mysql
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
          - '8080:80'
        volumes: 
          - /sessions
        networks:
            webphp:
                ipv4_address: 10.201.0.5
    redis:
        container_name: c-redis
        image: redis
        restart: always
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - '6379:6379'
        networks:
            webphp:
                ipv4_address: 10.201.0.6
    memcached:
        container_name: c-memcached
        image: memcached
        ports:
            - "11211:11211"
    node:
        container_name: c-node
        build:
            context: ./node
            dockerfile: Dockerfile
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports: 
            - "3000:3000"
        volumes:
            - /usr/src/app/node_modules
            - ./node:/usr/src/app
