version: '3'
services:
  node:
    container_name: c-node
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
